### ISSUE TITLE
Error in dask-core 2021.3.1 manifest entry in repodata.json

### ISSUE THREAD

**Issue by jamesp** [AnacondaRecipes/dask-core-feedstock#3]
Not sure if this is the correct place to report this, please redirect me if not.

There appears to be an error in dask-core dependencies the [main/noarch/repodata.json](https://repo.anaconda.com/pkgs/main/noarch/repodata.json) for anaconda main.  

There is an errant space in the partd dependency:
`"partd >= 0.3.10"` --- SHOULD BE ---> `"partd >=0.3.10"`

This is causing failure to resolve the dependencies with error message:
`conda.exceptions.InvalidSpecError: Invalid spec: >=`

Extract below:
```
    "dask-core-2021.3.1-pyhd3eb1b0_0.tar.bz2": {
      "build": "pyhd3eb1b0_0",
      "build_number": 0,
      "depends": [
        "python >=3.7",
        "cloudpickle >=1.1.1",
        "fsspec >=0.6.0",
        "partd >= 0.3.10",
        "pyyaml",
        "toolz >=0.8.2"
      ],
      "license": "BSD-3-Clause",
      "md5": "354c8113fa8f1e3eb1f18cec0653ccd2",
      "name": "dask-core",
      "noarch": "python",
      "sha256": "ab07520f2ad40ac3a3c85f99b37a1988ab583d3aa1878d3c1ec3405e9418db88",
      "size": 729308,
      "subdir": "noarch",
      "timestamp": 1617117402827,
      "version": "2021.3.1"
    },
```

**Comment by jamesp** [comment]
Hi @chenghlee, is this the right place to raise this issue? I'm unsure where in the build process the additional space is being added to the dependency specification as it looks correct in the `meta.yaml` file.

**Comment by jamesp** [comment]
I'm assuming this is related to #1 and #2, as you can see in the above extract of the repodata.json, the dependencies have been fixed, but the build number remains at 0, and there is no build=1 in the repodata

**Comment by jamesp** [comment]
Many thanks 👍

**Comment by chenghlee** [comment]
You're welcome. Just be aware that it may take an hour or so for the changes to propagate through the CDN.
